version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - python -m venv evnv
      - source venv/bin/activate
      - export HERE=```pwd```
      - cd venv/lib/python3.6/site-packages
      - zip -r9 /tmp/auto-grader-build.zip *
      - cd ${HERE}
      - zip -g /tmp/auto-grader-build.zip lambda_function.py
      - mv /tmp/auto-grader-build.zip github-authorizer.zip
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - github-authorizer.zip
